---
development:
  dialect: "sqlite3"
  database: ./persistence/dev.sqlite

test:
  dialect: "sqlite3"
  database: ./persistence/test.sqlite

production:
  dialect: "sqlite3"
  database: ./persistence/prod.sqlite
